### ISSUE TITLE
这不是用的insightFace的网络吧?

### ISSUE THREAD

**Issue by h3clikejava** [littleWayne/Mtcnn_insightface#1]
看了源码如果我没理解错应该是NCNN + (MTCTT + MobileFaceNet)实现的吧?
没明白哪里使用了insightFace？
另外C++层用了ArcSoft的命名，但是貌似和虹软一点关系也没有吧?
然后特征计算是用的什么算法呢?感觉就是特征相乘之后求和???

```
float calcSimilar(std::vector<float> feature1, std::vector<float> feature2)
{
    //assert(feature1.size() == feature2.size());
    float sim = 0.0;
    for (int i = 0; i < feature1.size(); i++)
        sim += feature1[i] * feature2[i];
    return sim;
}
```

因为我对JNI不是很熟，最后没有编译跑通，不知道准确率如何。

**Comment by littleWayne** [comment]
> 看了源码如果我没理解错应该是NCNN + (MTCTT + MobileFaceNet)实现的吧?
> 没明白哪里使用了insightFace？
> 另外C++层用了ArcSoft的命名，但是貌似和虹软一点关系也没有吧?
> 然后特征计算是用的什么算法呢?感觉就是特征相乘之后求和???
> 
> ```
> float calcSimilar(std::vector<float> feature1, std::vector<float> feature2)
> {
>     //assert(feature1.size() == feature2.size());
>     float sim = 0.0;
>     for (int i = 0; i < feature1.size(); i++)
>         sim += feature1[i] * feature2[i];
>     return sim;
> }
> ```
> 
> 因为我对JNI不是很熟，最后没有编译跑通，不知道准确率如何。

这个c++和ncnn包括网络的部分都不是自己写的，当时是拿的另一份开源代码来用的，
另外当时做这个的时候不会c++，不会java，不会android，四天拼出来的，不要太在意细节，
ncnn+arcface那一部分你可以自行在github上找

**Comment by h3clikejava** [comment]
666
